version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "7500:27017"

  backend:
    build: ./backend
    image: back
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    image: front
    # ports:
    #   - "9000:5173"
    depends_on:
      - backend
