version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    image: ramjirv3217/backend-image:latest
    deploy:
      replicas: 2
    ports:
      - "5000-5001:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/recipes
      - PORT=5000
    networks:
      - app-network

  frontend:
    image: ramjirv3217/frontend-image:latest
    deploy:
      replicas: 2
    ports:
      - "5173-5174:5173"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
